// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxOIKLe07XyPpeQ5uenwsyVVXr3iv72_A',
    appId: '1:796869892588:web:ab401686d3eea91cd388c9',
    messagingSenderId: '796869892588',
    projectId: 'authmailpassword',
    authDomain: 'authmailpassword.firebaseapp.com',
    storageBucket: 'authmailpassword.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4juGhlCtTw6XFTTbfb-tBCKBWhY8tguY',
    appId: '1:796869892588:android:93cea391e4bf8ad0d388c9',
    messagingSenderId: '796869892588',
    projectId: 'authmailpassword',
    storageBucket: 'authmailpassword.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC2ut1vosgLxxfgGiOnEUzofYAcJgtEWAI',
    appId: '1:796869892588:ios:ce39614b4ae1b2eed388c9',
    messagingSenderId: '796869892588',
    projectId: 'authmailpassword',
    storageBucket: 'authmailpassword.appspot.com',
    iosClientId: '796869892588-c1nhvqsugpvpqfkvffnpgumpun501mi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.webdiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC2ut1vosgLxxfgGiOnEUzofYAcJgtEWAI',
    appId: '1:796869892588:ios:ce39614b4ae1b2eed388c9',
    messagingSenderId: '796869892588',
    projectId: 'authmailpassword',
    storageBucket: 'authmailpassword.appspot.com',
    iosClientId: '796869892588-c1nhvqsugpvpqfkvffnpgumpun501mi2.apps.googleusercontent.com',
    iosBundleId: 'com.example.webdiary',
  );
}
